import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import { openUrl } from "@tauri-apps/plugin-opener";
import { LibraryPanel } from "./components/LibraryPanel";
import { PackPanel } from "./components/PackPanel";
import { SettingsModal } from "./components/SettingsModal";
import { Toast } from "./components/Toast";
import { TopBar, type AppView } from "./components/TopBar";
import { TransferRail } from "./components/TransferRail";
import { TrainerPanel } from "./components/TrainerPanel";
import { PlayerAnalyzer } from "./components/PlayerAnalyzer";
import { BackgroundEditor } from "./components/BackgroundEditor";
import { ProjectsPanel } from "./components/ProjectsPanel";
import type { TrainingCandidate } from "./logic/playerAnalysis";
import { deleteProjectFile, estimatePackSize, generatePack, listProjectFiles, loadProjectFile, loadSettings, pickBackground, pickDirectory, pickFfmpeg, saveProjectFile, saveSettings, scanFolder, type SavedProject } from "./api";
import type { BeatmapSet, PackItem, Settings } from "./types";

const defaults:Settings={language:"en",songsFolder:"",outputFolder:"",ffmpegPath:"",packName:"My pack",author:"",theme:"rose",backgroundImage:"",backgroundOpacity:.16};
const themeColors:Record<Settings["theme"],[string,string]>={rose:["#ff5aa5","#9a65ff"],violet:["#a970ff","#6948ff"],ocean:["#31b8ff","#5065ff"],emerald:["#37d6a0","#2e8dca"],amber:["#ffac45","#f05286"]};
type Notice={kind:"success"|"error";title:string;message:string};
type Draft={pack:PackItem[];settings:Settings};
const readDraft=():Draft|null=>{try{return JSON.parse(localStorage.getItem("pack-studio-current-draft")||"null")}catch{return null}};
export default function App(){
 const [settings,setSettings]=useState(defaults),[sets,setSets]=useState<BeatmapSet[]>([]),[pack,setPack]=useState<PackItem[]>([]),[projects,setProjects]=useState<SavedProject[]>([]),[selectedSets,setSelectedSets]=useState(new Set<string>()),[scanning,setScanning]=useState(false),[generating,setGenerating]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[notice,setNotice]=useState<Notice|null>(null),[view,setView]=useState<AppView>("pack"),[estimatedSizeBytes,setEstimatedSizeBytes]=useState(0),[newSetIds,setNewSetIds]=useState(new Set<string>()),[hydrated,setHydrated]=useState(false);
 const pickedIds=useMemo(()=>new Set(pack.map(x=>x.difficulty.id)),[pack]);
 const showError=(e:unknown)=>setNotice({kind:"error",title:"Something went wrong",message:e instanceof Error?e.message:String(e)});
 const refreshProjects=()=>listProjectFiles().then(setProjects).catch(showError);
 useEffect(()=>{loadSettings().then(s=>{const draft=readDraft();setSettings({...defaults,...s,...draft?.settings});setPack(draft?.pack||[]);setHydrated(true)}).catch(showError);refreshProjects();},[]);
 useEffect(()=>{const timer=setTimeout(()=>saveSettings(settings).catch(()=>{}),350);return()=>clearTimeout(timer)},[settings]);
 useEffect(()=>{const timer=setTimeout(()=>estimatePackSize(pack).then(setEstimatedSizeBytes).catch(()=>setEstimatedSizeBytes(0)),250);return()=>clearTimeout(timer)},[pack]);
 useEffect(()=>{if(!hydrated)return;const timer=setTimeout(()=>localStorage.setItem("pack-studio-current-draft",JSON.stringify({pack,settings} satisfies Draft)),400);return()=>clearTimeout(timer)},[hydrated,pack,settings]);
 const patchSettings=(patch:Partial<Settings>)=>setSettings(s=>({...s,...patch}));
 const chooseDirectory=async(field:"songsFolder"|"outputFolder")=>{const value=await pickDirectory(field==="songsFolder"?"Choose osu! Songs folder":"Choose output folder");if(value)patchSettings({[field]:value})};
 const chooseMapBackground=async(id:string)=>{const value=await pickBackground();if(value)setPack(items=>items.map(item=>item.difficulty.id===id?{...item,customBackgroundPath:value}:item))};
 const doScan=async()=>{if(!settings.songsFolder)return;setScanning(true);try{const data=await scanFolder(settings.songsFolder),old=new Map(sets.map(s=>[s.id,s])),added=new Set(data.filter(s=>!old.has(s.id)).map(s=>s.id)),difficulties=new Map(data.flatMap(set=>set.difficulties.map(difficulty=>[difficulty.id,{set,difficulty}])));setSets(data);setPack(items=>items.map(item=>{const found=difficulties.get(item.difficulty.id);return found?{...item,set:found.set,difficulty:found.difficulty}:item}));setNewSetIds(sets.length?added:new Set());setSelectedSets(new Set());setNotice({kind:"success",title:"Scan complete",message:`Found ${data.length} beatmapsets.`})}catch(e){showError(e)}finally{setScanning(false)}};
 const addDifficulty=(set:BeatmapSet,id:string)=>{const difficulty=set.difficulties.find(d=>d.id===id);if(difficulty&&!pickedIds.has(id))setPack(old=>[...old,{set,difficulty,rate:1,pitch:0,selected:false}])};
 const addSet=(set:BeatmapSet)=>setPack(old=>{const ids=new Set(old.map(x=>x.difficulty.id));return [...old,...set.difficulties.filter(d=>!ids.has(d.id)).map(difficulty=>({set,difficulty,rate:1,pitch:0,selected:false}))]});
 const saveProject=async(kind:"manual"|"auto"="manual")=>{const suggested=`${settings.packName} ${kind==="auto"?"autosave":"project"}`;const name=kind==="manual"?window.prompt("Project name",suggested):suggested;if(!name)return;try{await saveProjectFile({name,kind,pack,settings});await refreshProjects();setNotice({kind:"success",title:"Project saved",message:name})}catch(e){showError(e)}};
 const openProject=async(project:SavedProject)=>{try{const saved=await loadProjectFile(project.id);setPack(saved.pack||[]);setSettings(current=>({...current,...saved.settings}));setView("pack");setNotice({kind:"success",title:"Project loaded",message:saved.name})}catch(e){showError(e)}};
 const doGenerate=async()=>{setGenerating(true);try{const report=await generatePack(settings,pack);await saveProject("auto");setNotice({kind:"success",title:"Pack is ready",message:`${report.difficulties} maps saved in ${report.outputPath}`})}catch(e){showError(e)}finally{setGenerating(false)}};
 const createTrainerMap=async(item:PackItem)=>{setGenerating(true);try{const report=await generatePack({...settings,packName:`${item.set.title} Trainer`},[item]);await saveProject("auto");setNotice({kind:"success",title:"Trainer map is ready",message:report.outputPath})}catch(e){showError(e)}finally{setGenerating(false)}};
 const sendTrainingToPack=(candidates:TrainingCandidate[])=>{setPack(old=>{const ids=new Set(old.map(x=>x.difficulty.id));return [...old,...candidates.filter(x=>!ids.has(x.difficulty.id)).map(x=>({set:x.set,difficulty:x.difficulty,rate:x.rate,pitch:0,selected:false}))]});setView("pack")};
 const colors=themeColors[settings.theme]||themeColors.rose,themeStyle={"--accent":colors[0],"--accent-2":colors[1]} as CSSProperties,backgroundUrl=settings.backgroundImage?convertFileSrc(settings.backgroundImage):undefined;
 const updateItem=(id:string,patch:Partial<PackItem>)=>setPack(items=>items.map(item=>item.difficulty.id===id?{...item,...patch}:item));
 return <div className="app-shell" style={themeStyle}>{backgroundUrl&&<div className="theme-background" style={{backgroundImage:`url(${backgroundUrl})`,opacity:settings.backgroundOpacity}}/>}<div className="ambient one"/><div className="ambient two"/><TopBar path={settings.songsFolder} count={sets.length} scanning={scanning} onPick={()=>chooseDirectory("songsFolder")} onScan={doScan} onSettings={()=>setSettingsOpen(true)} view={view} onViewChange={setView} language={settings.language}/>{view==="pack"?<main className="workspace"><LibraryPanel sets={sets} picked={pickedIds} selectedSets={selectedSets} newSetIds={newSetIds} language={settings.language} onToggle={id=>setSelectedSets(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next})} onAddSet={addSet} onAddDifficulty={addDifficulty}/><TransferRail addDisabled={!selectedSets.size} removeDisabled={!pack.some(x=>x.selected)} language={settings.language} onAddSelected={()=>{sets.filter(s=>selectedSets.has(s.id)).forEach(addSet);setSelectedSets(new Set())}} onRemoveSelected={()=>setPack(p=>p.filter(x=>!x.selected))}/><PackPanel items={pack} settings={settings} language={settings.language} generating={generating} onSettings={patchSettings} onPickOutput={()=>chooseDirectory("outputFolder")} onToggle={id=>updateItem(id,{selected:!pack.find(x=>x.difficulty.id===id)?.selected})} onRemove={id=>setPack(p=>p.filter(x=>x.difficulty.id!==id))} onChange={updateItem} onGenerate={doGenerate}/><TrainerPanel items={pack} estimatedSizeBytes={estimatedSizeBytes} ffmpegPath={settings.ffmpegPath} language={settings.language} onChange={updateItem} onCreate={createTrainerMap}/></main>:view==="backgrounds"?<BackgroundEditor items={pack} language={settings.language} onPick={chooseMapBackground} onPickOverlay={pickBackground} onChange={updateItem} onApplyAll={patch=>setPack(items=>items.map(item=>({...item,...patch})))} />:view==="projects"?<ProjectsPanel projects={projects} language={settings.language} onSave={()=>saveProject()} onLoad={openProject} onDelete={async id=>{await deleteProjectFile(id);refreshProjects()}}/>:<PlayerAnalyzer sets={sets} language={settings.language} onSendToPack={sendTrainingToPack}/>}<div className="statusbar"><span><i/>Local Tauri mode</span><span>{pack.length} difficulties in pack</span><a href="https://osu.ppy.sh/users/31245051" onClick={event=>{event.preventDefault();void openUrl("https://osu.ppy.sh/users/31245051")}}>Created by Rotrix</a></div>{settingsOpen&&<SettingsModal settings={settings} onChange={patchSettings} onPickFfmpeg={async()=>{const path=await pickFfmpeg();if(path)patchSettings({ffmpegPath:path})}} onPickBackground={async()=>{const path=await pickBackground();if(path)patchSettings({backgroundImage:path})}} onSaveProject={()=>saveProject()} onLoadProject={()=>{setSettingsOpen(false);setView("projects")}} onClearProject={()=>setView("projects")} onClose={()=>setSettingsOpen(false)}/>} {notice&&<Toast {...notice} onClose={()=>setNotice(null)}/>}</div>
}
