import { Copy, ImagePlus, Images, Layers3, RotateCcw, Trash2 } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import type { BackgroundEffects, BackgroundOverlay, PackItem } from "../types";

const ALL_BACKGROUNDS = "__all_backgrounds__";
const fileUrl = (path?: string) => path ? convertFileSrc(path) : undefined;
const backgroundFor = (item: PackItem) => item.customBackgroundPath || item.difficulty.backgroundPath || item.set.backgroundPath;
const cleanEffects: BackgroundEffects = { preset:"none", brightness:1, contrast:1, saturation:1, blur:0, hue:0, vignette:0, glitch:0, grain:0, sharpen:0, pixelate:0, sepia:0, invert:false };
const presets: Array<{id:BackgroundEffects["preset"];name:string;effects:Partial<BackgroundEffects>}> = [
  {id:"none",name:"Original",effects:cleanEffects},{id:"glitch",name:"Glitch",effects:{contrast:1.25,saturation:1.35,hue:8,vignette:.2,glitch:12,sharpen:.4}},{id:"vhs",name:"VHS",effects:{contrast:1.12,saturation:.82,hue:-6,vignette:.5,glitch:5,grain:12,blur:.35}},{id:"neon",name:"Neon",effects:{brightness:1.05,contrast:1.3,saturation:1.8,hue:18,vignette:.35,sharpen:.7}},{id:"ice",name:"Ice",effects:{brightness:1.06,contrast:1.18,saturation:1.3,hue:155,vignette:.2,sharpen:.45}},{id:"inferno",name:"Inferno",effects:{brightness:.98,contrast:1.3,saturation:1.75,hue:-28,vignette:.5,grain:4}},{id:"mono",name:"Mono",effects:{contrast:1.2,saturation:0,vignette:.45,grain:3}},{id:"vintage",name:"Vintage",effects:{brightness:.95,contrast:1.08,saturation:.72,hue:-14,vignette:.55,grain:5,sepia:.7}},{id:"dream",name:"Dream",effects:{brightness:1.08,contrast:.9,saturation:1.28,blur:1.5,hue:22,vignette:.2}},{id:"pixel",name:"Pixel",effects:{contrast:1.12,saturation:1.25,pixelate:8,sharpen:.5}}
];
type Props = { items:PackItem[]; language:"en"|"pl"; onChange:(id:string,patch:Partial<PackItem>)=>void; onPick:(id:string)=>void; onPickOverlay:()=>Promise<string|null>; onApplyAll:(patch:Partial<PackItem>)=>void };

export function BackgroundEditor({items,language,onChange,onPick,onPickOverlay,onApplyAll}:Props) {
  const pl=language==="pl";
  const [activeId,setActiveId]=useState(""),[activeOverlay,setActiveOverlay]=useState(""),[confirmApply,setConfirmApply]=useState(false);
  const [globalDraft,setGlobalDraft]=useState<{effects:BackgroundEffects;overlays:BackgroundOverlay[]}>({effects:cleanEffects,overlays:[]});
  const frame=useRef<HTMLDivElement>(null),drag=useRef<{id:string;rect:DOMRect}|null>(null);
  const allMode=activeId===ALL_BACKGROUNDS;
  useEffect(()=>{if(activeId&&!allMode&&!items.some(item=>item.difficulty.id===activeId))setActiveId("")},[items,activeId,allMode]);
  const selected=useMemo(()=>items.find(item=>item.difficulty.id===activeId),[items,activeId]);
  const example=useMemo(()=>items.find(item=>backgroundFor(item))||items[0],[items]);
  const active=allMode?example:selected;
  if(!items.length)return <main className="background-editor empty-background-editor"><Images/><strong>{pl?"Dodaj mapę do paczki":"Add a map to the pack"}</strong></main>;
  const effects=allMode?globalDraft.effects:{...cleanEffects,...active?.backgroundEffects};
  const overlays=allMode?globalDraft.overlays:active?.overlays||[];
  const updateEffects=(patch:Partial<BackgroundEffects>)=>{
    const next={...effects,...patch,preset:patch.preset??"none"};
    if(allMode)setGlobalDraft(draft=>({...draft,effects:next})); else if(active)onChange(active.difficulty.id,{backgroundEffects:next});
  };
  const choosePreset=(preset:typeof presets[number])=>updateEffects({...cleanEffects,...preset.effects,preset:preset.id});
  const updateOverlay=(id:string,patch:Partial<BackgroundOverlay>)=>{
    const next=overlays.map(layer=>layer.id===id?{...layer,...patch}:layer);
    if(allMode)setGlobalDraft(draft=>({...draft,overlays:next})); else if(active)onChange(active.difficulty.id,{overlays:next});
  };
  const removeOverlay=(id:string)=>{
    const next=overlays.filter(layer=>layer.id!==id);
    if(allMode)setGlobalDraft(draft=>({...draft,overlays:next})); else if(active)onChange(active.difficulty.id,{overlays:next});
    if(activeOverlay===id)setActiveOverlay("");
  };
  const addOverlay=async()=>{const path=await onPickOverlay();if(!path)return;const layer={id:crypto.randomUUID(),path,opacity:.8,scale:.3,x:.5,y:.5};if(allMode)setGlobalDraft(draft=>({...draft,overlays:[...draft.overlays,layer]}));else if(active)onChange(active.difficulty.id,{overlays:[...(active.overlays||[]),layer]});};
  const dragMove=(event:React.PointerEvent)=>{if(!drag.current)return;const rect=drag.current.rect;updateOverlay(drag.current.id,{x:Math.max(0,Math.min(1,(event.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(event.clientY-rect.top)/rect.height))})};
  const selectAll=()=>{setActiveId(ALL_BACKGROUNDS);setActiveOverlay("");setConfirmApply(false)};
  const saveAll=()=>{onApplyAll({backgroundEffects:globalDraft.effects,overlays:globalDraft.overlays});setConfirmApply(false);setActiveId("")};
  return <main className="background-editor"><aside className="background-map-list"><div><span className="eyebrow">BACKGROUND EDITOR</span><h2>{pl?"Mapy w paczce":"Maps in pack"}</h2></div>
    <button className={`all-backgrounds-item ${allMode?"active":""}`} onClick={selectAll}><span className="background-thumb all-backgrounds-thumb"><Layers3/></span><span><strong>{pl?"Wszystkie backgroundy":"All backgrounds"}</strong><small>{pl?"Jedna konfiguracja dla całej paczki":"One saved configuration for the whole pack"}</small></span><i>{pl?"globalnie":"global"}</i></button>
    {items.map(item=><button key={item.difficulty.id} className={item.difficulty.id===activeId?"active":""} onClick={()=>{setActiveId(item.difficulty.id);setActiveOverlay("")}}><span className="background-thumb" style={{backgroundImage:`url(${fileUrl(backgroundFor(item))||""})`}}/><span><strong>{item.set.title}</strong><small>{item.set.artist} · [{item.difficulty.version}]</small></span>{(item.customBackgroundPath||item.overlays?.length||item.backgroundEffects)&&<i>edited</i>}</button>)}</aside>
  <section className="background-workbench dashboard-card">{!active?<div className="background-empty-selection"><Images/><strong>{pl?"Wybierz mapę z listy":"Choose a map from the list"}</strong><span>{pl?"Podgląd pozostaje pusty, dopóki nie wybierzesz mapy.":"The showcase stays empty until you select a map."}</span></div>:<>
    <div className="card-title"><Images/><span>{allMode?(pl?"Wszystkie backgroundy":"All backgrounds"):pl?"Edytor backgroundu":"Background editor"}</span>{allMode?<button className="btn primary compact" onClick={()=>setConfirmApply(true)}><Copy/>{pl?"Zapisz dla wszystkich":"Save for all"}</button>:<button className="btn secondary compact" onClick={selectAll}><Copy/>{pl?"Edytuj wszystkie":"Edit all"}</button>}</div>
    <div ref={frame} onPointerMove={dragMove} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null} className={`background-preview-frame ${effects.glitch>0?"has-glitch":""}`}><div key={active.difficulty.id} className="background-preview" style={backgroundFor(active)?{backgroundImage:`url(${fileUrl(backgroundFor(active))})`,filter:`brightness(${effects.brightness}) contrast(${effects.contrast}) saturate(${effects.saturation}) blur(${effects.blur}px) hue-rotate(${effects.hue}deg) ${effects.invert?"invert(1)":""}`} : undefined}>{!backgroundFor(active)&&<><Images/><span>{pl?"Ta mapa nie ma backgroundu":"This map has no background"}</span></>}</div>{overlays.map(layer=><img key={layer.id} draggable={false} className={`background-overlay-preview ${activeOverlay===layer.id?"selected":""}`} src={fileUrl(layer.path)} alt="Overlay" onPointerDown={event=>{if(!frame.current)return;event.preventDefault();frame.current.setPointerCapture(event.pointerId);drag.current={id:layer.id,rect:frame.current.getBoundingClientRect()};setActiveOverlay(layer.id)}} style={{left:`${layer.x*100}%`,top:`${layer.y*100}%`,width:`${layer.scale*100}%`,opacity:layer.opacity,transform:"translate(-50%,-50%)"}}/>)}{effects.vignette>0&&<i style={{opacity:effects.vignette}}/>}</div>
    <div className="background-effects"><div className="effect-presets">{presets.map(p=><button key={p.id} className={effects.preset===p.id?"active":""} onClick={()=>choosePreset(p)}>{p.name}</button>)}</div><div className="effect-sliders"><Effect label={pl?"Jasność":"Brightness"} value={effects.brightness} min={.5} max={1.5} step={.01} onChange={v=>updateEffects({brightness:v})}/><Effect label={pl?"Kontrast":"Contrast"} value={effects.contrast} min={.5} max={2} step={.01} onChange={v=>updateEffects({contrast:v})}/><Effect label="Saturation" value={effects.saturation} min={0} max={3} step={.01} onChange={v=>updateEffects({saturation:v})}/><Effect label="Hue" value={effects.hue} min={-180} max={180} step={1} onChange={v=>updateEffects({hue:v})}/><Effect label="Blur" value={effects.blur} min={0} max={12} step={.1} onChange={v=>updateEffects({blur:v})}/><Effect label="Vignette" value={effects.vignette} min={0} max={1} step={.01} onChange={v=>updateEffects({vignette:v})}/><Effect label="Grain" value={effects.grain} min={0} max={30} step={1} onChange={v=>updateEffects({grain:v})}/><label className="invert-effect"><span>Invert</span><input type="checkbox" checked={effects.invert} onChange={e=>updateEffects({invert:e.target.checked})}/></label></div></div>
    <div className="overlay-editor"><div className="overlay-heading"><Layers3/><span><strong>{pl?"Warstwy obrazu":"Image layers"}</strong><small>{allMode?(pl?"Zmiany są tylko w wersji roboczej, dopóki ich nie zapiszesz.":"These changes are a draft until you save them for all maps."):(pl?"Przeciągaj obraz bezpośrednio w podglądzie.":"Drag an image directly in the preview.")}</small></span><button className="btn secondary" onClick={addOverlay}><ImagePlus/>{pl?"Dodaj warstwę":"Add layer"}</button></div>{overlays.map((layer,index)=><div className="overlay-row" key={layer.id}><button className={activeOverlay===layer.id?"active":""} onClick={()=>setActiveOverlay(layer.id)}>#{index+1} {layer.path.split(/[\\/]/).pop()}</button><Effect label={pl?"Krycie":"Opacity"} value={layer.opacity} min={0} max={1} step={.01} onChange={v=>updateOverlay(layer.id,{opacity:v})}/><Effect label={pl?"Skala":"Scale"} value={layer.scale} min={.05} max={3} step={.01} onChange={v=>updateOverlay(layer.id,{scale:v})}/><button className="icon-btn" onClick={()=>removeOverlay(layer.id)}><Trash2/></button></div>)}</div>
    <div className="background-info"><div><strong>{allMode?(pl?"Zmiany globalne":"Global changes"):active.set.title}</strong><span>{allMode?(pl?"Preview używa przykładowego tła z paczki.":"Preview uses an example background from this pack."):`${active.set.artist} · (${active.set.creator}) · [${active.difficulty.version}]`}</span><small>{allMode?(pl?"Zapis nadpisze efekty i warstwy obrazów na wszystkich mapach.":"Saving replaces effects and image layers on every map."):(backgroundFor(active)||"No image file")}</small></div>{!allMode&&<div><button className="btn primary" onClick={()=>onPick(active.difficulty.id)}><ImagePlus/>{pl?"Zmień tło":"Change background"}</button><button className="btn secondary" onClick={()=>onChange(active.difficulty.id,{customBackgroundPath:undefined,overlays:[],backgroundEffects:cleanEffects})}><RotateCcw/>Reset</button></div>}</div>
  </>}</section>{confirmApply&&<div className="modal-backdrop"><section className="modal global-apply-modal"><div className="modal-title"><div className="settings-icon"><Copy/></div><div><span className="eyebrow">GLOBAL BACKGROUNDS</span><h2>{pl?"Zapisać dla wszystkich map?":"Save changes for every map?"}</h2></div></div><p>{pl?"Ta operacja nadpisze dotychczasowe efekty i warstwy obrazów we wszystkich mapach tej paczki. Nie zmieni samych plików tła.":"This replaces existing effects and image layers on every map in this pack. The background image files themselves stay unchanged."}</p><div className="global-apply-actions"><button className="btn secondary" onClick={()=>setConfirmApply(false)}>{pl?"Anuluj":"Cancel"}</button><button className="btn primary" onClick={saveAll}>{pl?"Tak, zapisz wszędzie":"Yes, save everywhere"}</button></div></section></div>}</main>;
}
function Effect({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}){return <label><span>{label}<b>{Number(value).toFixed(step<1?2:0)}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={e=>onChange(Number(e.target.value))}/></label>}
