import { ImagePlus, Images, Layers3, RotateCcw, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import type { BackgroundEffects, PackItem } from "../types";

const fileUrl = (path?: string) => path ? encodeURI(`file:///${path.replace(/\\/g, "/")}`) : undefined;
const cleanEffects: BackgroundEffects = { preset:"none",brightness:1,contrast:1,saturation:1,blur:0,hue:0,vignette:0,glitch:0,grain:0,sharpen:0,pixelate:0,sepia:0,invert:false,overlayOpacity:.8,overlayScale:.3,overlayX:.5,overlayY:.5 };
const presets: Array<{id:BackgroundEffects["preset"];name:string;effects:Partial<BackgroundEffects>}> = [
  {id:"none",name:"Original",effects:cleanEffects},{id:"glitch",name:"Glitch",effects:{contrast:1.25,saturation:1.35,hue:8,vignette:.2,glitch:12,sharpen:.4}},
  {id:"vhs",name:"VHS",effects:{contrast:1.12,saturation:.82,hue:-6,vignette:.5,glitch:5,grain:12,blur:.35}},{id:"neon",name:"Neon",effects:{brightness:1.05,contrast:1.3,saturation:1.8,hue:18,vignette:.35,sharpen:.7}},
  {id:"ice",name:"Ice",effects:{brightness:1.06,contrast:1.18,saturation:1.3,hue:155,vignette:.2,sharpen:.45}},{id:"inferno",name:"Inferno",effects:{brightness:.98,contrast:1.3,saturation:1.75,hue:-28,vignette:.5,grain:4}},
  {id:"mono",name:"Mono",effects:{contrast:1.2,saturation:0,vignette:.45,grain:3}},{id:"vintage",name:"Vintage",effects:{brightness:.95,contrast:1.08,saturation:.72,hue:-14,vignette:.55,grain:5,sepia:.7}},
  {id:"dream",name:"Dream",effects:{brightness:1.08,contrast:.9,saturation:1.28,blur:1.5,hue:22,vignette:.2}},{id:"pixel",name:"Pixel",effects:{contrast:1.12,saturation:1.25,pixelate:8,sharpen:.5}},
];

type Props = { items:PackItem[]; language:"en"|"pl"; onChange:(id:string,patch:Partial<PackItem>)=>void; onPick:(id:string)=>void; onPickOverlay:(id:string)=>void };

export function BackgroundEditor({items,language,onChange,onPick,onPickOverlay}:Props) {
  const pl=language==="pl";
  const [activeId,setActiveId]=useState(items[0]?.difficulty.id||"");
  useEffect(()=>{if(!items.some(item=>item.difficulty.id===activeId))setActiveId(items[0]?.difficulty.id||"")},[items,activeId]);
  const active=useMemo(()=>items.find(item=>item.difficulty.id===activeId)||items[0],[items,activeId]);
  if(!active)return <main className="background-editor empty-background-editor"><Images/><strong>{pl?"Dodaj mapę do paczki":"Add a map to the pack"}</strong><span>{pl?"Tutaj zmienisz background przed wygenerowaniem .osz.":"Edit its background here before generating the .osz file."}</span></main>;
  const preview=fileUrl(active.customBackgroundPath||active.set.backgroundPath), overlay=fileUrl(active.backgroundOverlayPath), effects={...cleanEffects,...active.backgroundEffects};
  const updateEffects=(patch:Partial<BackgroundEffects>)=>onChange(active.difficulty.id,{backgroundEffects:{...effects,...patch,preset:patch.preset??"none"}});
  const previewStyle = preview ? { backgroundImage:`url(${preview})`, filter:`brightness(${effects.brightness}) contrast(${effects.contrast}) saturate(${effects.saturation}) blur(${effects.blur}px) hue-rotate(${effects.hue}deg) ${effects.invert?"invert(1)":""}` } : undefined;
  const overlayStyle = overlay ? {left:`${effects.overlayX*100}%`,top:`${effects.overlayY*100}%`,width:`${effects.overlayScale*100}%`,opacity:effects.overlayOpacity,transform:"translate(-50%,-50%)"} : undefined;
  const choosePreset=(preset:typeof presets[number])=>onChange(active.difficulty.id,{backgroundEffects:{...cleanEffects,...preset.effects,preset:preset.id}});
  return <main className="background-editor">
    <aside className="background-map-list"><div><span className="eyebrow">BACKGROUND EDITOR</span><h2>{pl?"Mapy w paczce":"Maps in pack"}</h2></div>{items.map(item=><button key={item.difficulty.id} className={item.difficulty.id===active.difficulty.id?"active":""} onClick={()=>setActiveId(item.difficulty.id)}><span className="background-thumb" style={{backgroundImage:`url(${fileUrl(item.customBackgroundPath||item.set.backgroundPath)||""})`}}/><span><strong>{item.set.title}</strong><small>{item.set.artist} · [{item.difficulty.version}]</small></span>{(item.customBackgroundPath||item.backgroundOverlayPath)&&<i>edited</i>}</button>)}</aside>
    <section className="background-workbench dashboard-card">
      <div className="card-title"><Images/><span>{pl?"Edytor backgroundu":"Background editor"}</span><small>{pl?"warstwy i efekty zostaną zapisane w .osz":"layers and effects are saved to the .osz"}</small></div>
      <div className={`background-preview-frame ${effects.glitch>0?"has-glitch":""}`}><div className="background-preview" style={previewStyle}>{!preview&&<><Images/><span>Ta mapa nie ma backgroundu</span></>}</div>{overlay&&<img className="background-overlay-preview" src={overlay} alt="Warstwa" style={overlayStyle}/>} {effects.vignette>0&&<i style={{opacity:effects.vignette}}/>}</div>
      <div className="background-effects"><div className="effect-presets">{presets.map(preset=><button key={preset.id} className={effects.preset===preset.id?"active":""} onClick={()=>choosePreset(preset)}>{preset.name}</button>)}</div><div className="effect-sliders"><Effect label={pl?"Jasność":"Brightness"} value={effects.brightness} min={.5} max={1.5} step={.01} onChange={value=>updateEffects({brightness:value})}/><Effect label={pl?"Kontrast":"Contrast"} value={effects.contrast} min={.5} max={2} step={.01} onChange={value=>updateEffects({contrast:value})}/><Effect label={pl?"Kolory":"Saturation"} value={effects.saturation} min={0} max={3} step={.01} onChange={value=>updateEffects({saturation:value})}/><Effect label="Hue" value={effects.hue} min={-180} max={180} step={1} onChange={value=>updateEffects({hue:value})}/><Effect label="Blur" value={effects.blur} min={0} max={12} step={.1} onChange={value=>updateEffects({blur:value})}/><Effect label="Vignette" value={effects.vignette} min={0} max={1} step={.01} onChange={value=>updateEffects({vignette:value})}/><Effect label="Glitch" value={effects.glitch} min={0} max={20} step={1} onChange={value=>updateEffects({glitch:value})}/><Effect label="Grain" value={effects.grain} min={0} max={30} step={1} onChange={value=>updateEffects({grain:value})}/><Effect label="Sharp" value={effects.sharpen} min={0} max={2} step={.05} onChange={value=>updateEffects({sharpen:value})}/><Effect label="Pixel" value={effects.pixelate} min={0} max={24} step={1} onChange={value=>updateEffects({pixelate:value})}/><Effect label="Sepia" value={effects.sepia} min={0} max={1} step={.01} onChange={value=>updateEffects({sepia:value})}/><label className="invert-effect"><span>Invert</span><input type="checkbox" checked={effects.invert} onChange={event=>updateEffects({invert:event.target.checked})}/></label></div></div>
      <div className="overlay-editor"><div className="overlay-heading"><Layers3/><span><strong>{pl?"Zdjęcie na zdjęciu":"Image overlay"}</strong><small>{pl?"Dodaj logo, postać albo drugi obraz jako warstwę.":"Add a logo, character or another image as a layer."}</small></span><button className="btn secondary" onClick={()=>onPickOverlay(active.difficulty.id)}><ImagePlus/>{overlay?(pl?"Zmień warstwę":"Change layer"):(pl?"Dodaj warstwę":"Add layer")}</button>{overlay&&<button className="icon-btn" title="Remove layer" onClick={()=>onChange(active.difficulty.id,{backgroundOverlayPath:undefined})}><Trash2/></button>}</div>{overlay&&<div className="overlay-controls"><Effect label={pl?"Przezroczystość":"Opacity"} value={effects.overlayOpacity} min={0} max={1} step={.01} onChange={value=>updateEffects({overlayOpacity:value})}/><Effect label={pl?"Rozmiar":"Scale"} value={effects.overlayScale} min={.05} max={1} step={.01} onChange={value=>updateEffects({overlayScale:value})}/><Effect label="Position X" value={effects.overlayX} min={0} max={1} step={.01} onChange={value=>updateEffects({overlayX:value})}/><Effect label="Position Y" value={effects.overlayY} min={0} max={1} step={.01} onChange={value=>updateEffects({overlayY:value})}/></div>}</div>
      <div className="background-info"><div><strong>{active.set.title}</strong><span>{active.set.artist} · ({active.set.creator}) · [{active.difficulty.version}]</span><small>{active.customBackgroundPath||active.set.backgroundPath||(pl?"Brak pliku obrazu":"No image file")}</small></div><div><button className="btn primary" onClick={()=>onPick(active.difficulty.id)}><ImagePlus/>{pl?"Zmień tło":"Change background"}</button><button className="btn secondary" onClick={()=>onChange(active.difficulty.id,{customBackgroundPath:undefined,backgroundOverlayPath:undefined,backgroundEffects:cleanEffects})}><RotateCcw/>Reset</button></div></div>
    </section>
  </main>;
}

function Effect({label,value,min,max,step,onChange}:{label:string;value:number;min:number;max:number;step:number;onChange:(value:number)=>void}) { return <label><span>{label}<b>{Number(value).toFixed(step<1?2:0)}</b></span><input type="range" value={value} min={min} max={max} step={step} onChange={event=>onChange(Number(event.target.value))}/></label> }
