import { ChevronDown, ChevronRight, Disc3, Plus, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { convertFileSrc } from "@tauri-apps/api/core";
import type { BeatmapSet } from "../types";

type Props={sets:BeatmapSet[];picked:Set<string>;selectedSets:Set<string>;newSetIds:Set<string>;language:"en"|"pl";onToggle:(id:string)=>void;onAddSet:(set:BeatmapSet)=>void;onAddDifficulty:(set:BeatmapSet,difficultyId:string)=>void};

export function LibraryPanel({sets,picked,selectedSets,newSetIds,language,onToggle,onAddSet,onAddDifficulty}:Props) {
  const pl=language==="pl",[query,setQuery]=useState(""),[sort,setSort]=useState("title"),[mode,setMode]=useState("all"),[expanded,setExpanded]=useState<Set<string>>(new Set()),[visibleCount,setVisibleCount]=useState(100);
  const filtered=useMemo(()=>{const q=query.trim().toLocaleLowerCase();return sets.filter(s=>(!q||`${s.artist} ${s.title} ${s.creator} ${s.difficulties.map(d=>d.version).join(" ")}`.toLocaleLowerCase().includes(q))&&(mode==="all"||s.difficulties.some(d=>d.mode===Number(mode)))).sort((a,b)=>sort==="count"?b.difficulties.length-a.difficulties.length:a[sort as "artist"|"title"|"creator"].localeCompare(b[sort as "artist"|"title"|"creator"],language));},[sets,query,sort,mode,language]);
  useEffect(()=>setVisibleCount(100),[query,sort,mode,sets.length]);
  const visible=filtered.slice(0,visibleCount),toggleExpand=(id:string)=>setExpanded(old=>{const next=new Set(old);next.has(id)?next.delete(id):next.add(id);return next});
  return <section className="panel library-panel">
    <div className="panel-heading"><div><span className="eyebrow">{pl?"BIBLIOTEKA":"LIBRARY"}</span><h2>{pl?"Twoje mapy":"Your maps"}</h2></div><span className="count-chip">{filtered.length}</span></div>
    <div className="library-tools"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={pl?"Tytuł, artysta, mapper lub difficulty…":"Title, artist, mapper or difficulty…"}/></label><select value={mode} onChange={e=>setMode(e.target.value)} aria-label="Mode"><option value="all">{pl?"Wszystkie tryby":"All modes"}</option><option value="0">Standard</option><option value="1">Taiko</option><option value="2">Catch</option><option value="3">Mania</option></select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="Sort"><option value="title">{pl?"Tytuł A–Z":"Title A–Z"}</option><option value="artist">{pl?"Artysta A–Z":"Artist A–Z"}</option><option value="creator">Mapper A–Z</option><option value="count">{pl?"Najwięcej difficulty":"Most difficulties"}</option></select></div>
    <div className="map-list">{!sets.length&&<div className="empty"><Disc3/><strong>{pl?"Biblioteka jest pusta":"Library is empty"}</strong><span>{pl?"Wybierz folder Songs i uruchom skanowanie.":"Choose your osu! Songs folder and scan it."}</span></div>}{visible.map(set=>{const open=expanded.has(set.id),allPicked=set.difficulties.every(d=>picked.has(d.id));return <article className={`map-card ${selectedSets.has(set.id)?"selected":""} ${newSetIds.has(set.id)?"new-map":""}`} key={set.id}><div className="map-main"><button className="chevron" onClick={()=>toggleExpand(set.id)} aria-label="Expand">{open?<ChevronDown/>:<ChevronRight/>}</button><div className="cover" style={set.backgroundPath?{backgroundImage:`url(${coverUrl(set.backgroundPath)})`}:undefined}><Disc3/></div><div className="map-copy" onClick={()=>onToggle(set.id)}><strong>{set.title}</strong><span>{set.artist}</span><small>{set.creator} · {set.difficulties.length} difficulty</small></div>{newSetIds.has(set.id)&&<b className="new-badge">NEW</b>}<button className={`mini-add ${allPicked?"added":""}`} onClick={()=>onAddSet(set)} title={pl?"Dodaj cały beatmapset":"Add beatmapset"}><Plus size={16}/></button></div>{open&&<div className="diff-list">{set.difficulties.filter(d=>!query.trim()||`${d.version} ${set.title} ${set.artist} ${set.creator}`.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())).map((d,i)=><button key={d.id} className={picked.has(d.id)?"picked":""} onClick={()=>onAddDifficulty(set,d.id)}><span className={`dot d${Math.min(i,4)}`}/><span title={d.version}>{d.version}</span><small>{d.mode===0?"osu!standard":`mode ${d.mode}`}</small><Plus size={14}/></button>)}</div>}</article>})}{visible.length<filtered.length&&<button className="show-more" onClick={()=>setVisibleCount(count=>count+100)}>{pl?"Pokaż kolejne 100":"Show 100 more"}<small>{visible.length} / {filtered.length}</small></button>}</div>
  </section>;
}

function coverUrl(path:string){if("__TAURI_INTERNALS__" in window)return convertFileSrc(path);if(window.packStudio)return encodeURI(`file:///${path.replace(/\\/g,"/")}`);return ""}
