import { BarChart3, BrainCircuit, Download, Search, Send, Target, TrendingUp, UserRound } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { generateTraining, mapManiaTrackerToPlayerAnalysis, similarMaps, skillNames, type PlayerAnalysis, type SkillName, type TrainingCandidate } from "../logic/playerAnalysis";
import { loadSnapshots, LocalLibraryPlayerProvider, ManiaTrackerPlayerProvider, saveSnapshot } from "../services/playerProvider";
import { ManiaTrackerService } from "../services/maniaTrackerService";
import type { BeatmapSet } from "../types";

export function PlayerAnalyzer({ sets, onSendToPack, language }: { sets: BeatmapSet[]; onSendToPack: (items: TrainingCandidate[]) => void;language:"en"|"pl" }) {
  const pl=language==="pl";
  const [username,setUsername]=useState(""); const [data,setData]=useState<PlayerAnalysis|null>(null); const [error,setError]=useState(""); const [loading,setLoading]=useState(false);
  const [trackerUrl,setTrackerUrl]=useState(""); const [trackerLoading,setTrackerLoading]=useState(false); const [trackerStatus,setTrackerStatus]=useState("");
  const [skill,setSkill]=useState<SkillName>("Jack"),[keys,setKeys]=useState(4),[bpm,setBpm]=useState(200),[count,setCount]=useState(9),[minRate,setMinRate]=useState(.9),[maxRate,setMaxRate]=useState(1.1),[training,setTraining]=useState<TrainingCandidate[]>([]);
  const [similarTarget,setSimilarTarget]=useState("");
  const history=useMemo(()=>username?loadSnapshots(username):[],[username,data]);
  const allDifficulties=useMemo(()=>sets.flatMap(set=>set.difficulties.map(difficulty=>({set,difficulty}))).filter(x=>x.difficulty.metrics),[sets]);
  useEffect(()=>{const cached=new ManiaTrackerService().loadCachedProfile();if(cached){setTrackerUrl(cached.sourceUrl);setUsername(cached.username||"");setData(mapManiaTrackerToPlayerAnalysis(cached,sets));setTrackerStatus(pl?"Wczytano ostatni profil z cache.":"Loaded the last profile from cache.")}},[]);
  const run=async()=>{if(!username.trim()){setError(pl?"Wpisz nazwę gracza.":"Enter a player name.");return} if(!sets.length){setError(pl?"Najpierw przeskanuj bibliotekę map.":"Scan the map library first.");return} setLoading(true);setError("");try{const result=await new LocalLibraryPlayerProvider().analyze(username.trim(),sets);setData(result);saveSnapshot({username:username.trim(),capturedAt:Date.now(),estimatedPp:result.estimatedPp,maps:result.difficulties.length,medianBpm:result.medianBpm});}catch(e){setError(String(e))}finally{setLoading(false)}};
  const importTracker=async()=>{setTrackerLoading(true);setError("");setTrackerStatus("");try{const result=await new ManiaTrackerPlayerProvider().analyze(trackerUrl,sets);setData(result);setUsername(result.username);setTrackerStatus(pl?`Zaimportowano profil ${result.username}.`:`Imported ${result.username}. Missing values were left empty.`);saveSnapshot({username:result.username,capturedAt:Date.now(),estimatedPp:result.estimatedPp,maps:result.profile?.topPlayCount||result.difficulties.length,medianBpm:result.medianBpm});}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setTrackerLoading(false)}};
  const createTraining=()=>setTraining(generateTraining(sets,{skill,keys,bpm,count,minRate,maxRate}));
  const target=allDifficulties.find(x=>x.difficulty.id===similarTarget); const similar=target?similarMaps(target.difficulty,sets):[];
  return <main className="analyzer-view">
    <section className="analyzer-search"><div><span className="eyebrow">DAN CREATOR</span><h1>Know your playstyle</h1><p>Analyze your profile and generate a focused osu!mania training pack.</p></div><label><UserRound/><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="osu! username / user ID"/><button className="btn primary" onClick={run} disabled={loading}><Search/>{loading?"Analyzing…":"Analyze"}</button></label></section>
    <section className="mania-import dashboard-card"><div className="card-title"><Download/><span>{pl?"Import z Mania Tracker":"Import from Mania Tracker"}</span><small>{pl?"publiczny profil · cache ostatniego importu":"public profile · last import cache"}</small></div><div className="mania-import-row"><input aria-label="Mania Tracker URL" value={trackerUrl} onChange={e=>setTrackerUrl(e.target.value)} onKeyDown={e=>e.key==="Enter"&&importTracker()} placeholder="Mania Tracker URL"/><button className="btn primary" onClick={importTracker} disabled={trackerLoading}>{trackerLoading?<><span className="button-spinner"/>{pl?"Importowanie…":"Importing…"}</>:<><Download/>Import profile</>}</button></div>{trackerStatus&&<p className="import-status">{trackerStatus}</p>}</section>
    {error&&<div className="analyzer-error">{error}</div>}
    {!data?<section className="analyzer-empty"><BrainCircuit/><strong>{pl?"Przeskanuj bibliotekę i przeanalizuj profil":"Scan the library and analyze a profile"}</strong><span>{pl?"Statystyki lokalne korzystają z prawdziwych metryk beatmap.":"Local statistics use real beatmap metrics. Mania Tracker profiles can be imported above."}</span></section>:<>
      <section className="analyzer-grid top"><div className="dashboard-card profile-card"><div className="card-title"><UserRound/><span>Player profile</span><small>{data.source}</small></div><div className="profile-name">{data.profile?.avatar?<div className="profile-avatar"><img src={data.profile.avatar} alt=""/></div>:<div>{data.username.slice(0,2).toUpperCase()}</div>}<span><strong>{data.username}</strong><small>{data.profile?[data.profile.countryCode,data.profile.country].filter(Boolean).join(" · "):`${data.difficulties.length} przeanalizowanych difficulty`}</small></span></div><div className="stat-grid"><Stat label={data.profile?"Total PP":"Estimated PP"} value={formatNumber(data.estimatedPp)}/><Stat label="4K PP" value={formatNumber(data.pp4k)}/><Stat label="7K PP" value={formatNumber(data.pp7k)}/><Stat label="Keymode" value={data.commonKeys?`${data.commonKeys}K`:"—"}/><Stat label="Median BPM" value={optionalNumber(data.profile?.medianBpm,data.medianBpm)}/><Stat label="BPM range" value={range(data.profile?.minBpm??data.minBpm,data.profile?.maxBpm??data.maxBpm)}/><Stat label="Global rank" value={rank(data.profile?.globalRank)}/><Stat label="Accuracy" value={percent(data.profile?.accuracy)}/>{data.profile&&<><Stat label="Country rank" value={rank(data.profile.countryRank)}/><Stat label="Peak rank" value={rank(data.profile.peakRank)}/><Stat label="Peak date" value={date(data.profile.peakRankDate)}/><Stat label="Play count" value={formatNumber(data.profile.playCount)}/><Stat label="Play time" value={duration(data.profile.playTimeSeconds)}/><Stat label="Join date" value={date(data.profile.joinDate)}/><Stat label="Key split" value={keySplit(data.profile.keySplit)}/><Stat label="Most used mod" value={data.profile.mostUsedMod||"—"}/><Stat label="PP range" value={data.profile.ppRange?range(data.profile.ppRange.min,data.profile.ppRange.max):"—"}/><Stat label="Top plays" value={formatNumber(data.profile.topPlayCount)}/></>}</div></div><div className="dashboard-card skills-card"><div className="card-title"><Target/><span>Skills</span><small>{data.profile?"Mania Tracker + local fallback":"heuristic 0–100"}</small></div><Radar values={skillNames.map(name=>data.skills[name])}/><div className="skill-legend">{skillNames.map(name=><span key={name}><i style={{width:`${data.skills[name]}%`}}/><b>{name}</b><em>{data.skills[name]}</em></span>)}</div></div></section>
      <section className="analyzer-grid middle"><div className="dashboard-card"><div className="card-title"><BarChart3/><span>BPM profile</span></div><div className="histogram">{data.histogram.map((value,index)=><div key={index}><span style={{height:`${Math.max(5,value/Math.max(...data.histogram,1)*100)}%`}}/><b>{["100–150","150–200","200–250","250–300","300–350","350–400","400+"][index]}</b><em>{value}</em></div>)}</div><div className="bpm-summary"><Stat label="Median" value={data.medianBpm}/><Stat label="Comfort" value={`${data.comfortRange[0]}–${data.comfortRange[1]}`}/><Stat label="Min" value={data.minBpm}/><Stat label="Max" value={data.maxBpm}/></div></div><div className="dashboard-card"><div className="card-title"><TrendingUp/><span>Performance timeline</span><small>{history.length} snapshots</small></div><Timeline values={history.map(x=>x.estimatedPp)}/><div className="timeline-tabs"><button className="active">PP</button><button disabled>Rank · API</button><button disabled>Accuracy · API</button></div></div></section>
      <section className="profile-summary"><Summary title="Strong" items={data.strong}/><Summary title="Average" items={data.average}/><Summary title="Needs Practice" items={data.needsPractice}/></section>
    </>}
    <section className="dashboard-card training-builder"><div className="card-title"><BrainCircuit/><span>Generate Training Pack</span><small>dobór z lokalnej biblioteki</small></div><div className="training-form"><Select label="Skill" value={skill} onChange={v=>setSkill(v as SkillName)} options={skillNames.map(x=>[x,x])}/><NumberField label="Keymode" value={keys} onChange={setKeys} min={0} max={18}/><NumberField label="BPM" value={bpm} onChange={setBpm} min={0} max={500}/><NumberField label="Map count" value={count} onChange={setCount} min={3} max={30}/><NumberField label="Min rate" value={minRate} onChange={setMinRate} min={.1} max={3} step={.05}/><NumberField label="Max rate" value={maxRate} onChange={setMaxRate} min={.1} max={3} step={.05}/><button className="btn primary" onClick={createTraining}>Generate</button></div>{training.length>0&&<><div className="training-results">{(["Warmup","Practice","Challenge"] as const).map(tier=><div key={tier}><h3>{tier}</h3>{training.filter(x=>x.tier===tier).map(item=><article key={item.difficulty.id}><span><strong>{item.set.title}</strong><small>[{item.difficulty.version}] · {item.difficulty.metrics?.bpm} BPM · {item.difficulty.metrics?.keyCount}K</small></span><b>{item.rate.toFixed(2)}×</b></article>)}</div>)}</div><button className="btn send-pack" onClick={()=>onSendToPack(training)}><Send/>Send to Pack Studio</button></>}</section>
    <section className="dashboard-card similar-builder"><div className="card-title"><Search/><span>Find Similar Maps</span></div><select value={similarTarget} onChange={e=>setSimilarTarget(e.target.value)}><option value="">Wybierz difficulty…</option>{allDifficulties.slice(0,3000).map(x=><option key={x.difficulty.id} value={x.difficulty.id}>{x.set.artist} – {x.set.title} [{x.difficulty.version}]</option>)}</select>{similar.length>0&&<div className="similar-list">{similar.map(x=><article key={x.difficulty.id}><span>{x.set.title} [{x.difficulty.version}]</span><b>{x.similarity}%</b></article>)}</div>}</section>
  </main>;
}

function Stat({label,value}:{label:string;value:string|number}){return <div className="mini-stat"><span>{label}</span><strong>{value}</strong></div>}
const formatNumber=(value?:number)=>value===undefined||!Number.isFinite(value)?"—":new Intl.NumberFormat("pl-PL",{maximumFractionDigits:2}).format(value);
const optionalNumber=(external:number|undefined,fallback:number)=>external===undefined&&!fallback?"—":formatNumber(external??fallback);
const rank=(value?:number)=>value===undefined?"—":`#${formatNumber(value)}`;
const percent=(value?:number)=>value===undefined?"—":`${formatNumber(value)}%`;
const range=(min?:number,max?:number)=>min===undefined&&max===undefined?"—":`${min===undefined?"?":formatNumber(min)}–${max===undefined?"?":formatNumber(max)}`;
const date=(value?:string)=>{if(!value)return "—";const parsed=new Date(value);return Number.isNaN(parsed.getTime())?value:new Intl.DateTimeFormat("pl-PL").format(parsed)};
const duration=(seconds?:number)=>seconds===undefined?"—":`${Math.floor(seconds/3600).toLocaleString("pl-PL")} h`;
const keySplit=(value?:Record<string,number>)=>value?Object.entries(value).map(([key,count])=>`${key} ${count}`).join(" · "):"—";
function Summary({title,items}:{title:string;items:[SkillName,number][]}){return <div><h3>{title}</h3>{items.map(([name,value])=><span key={name}>{name}<b>{value}</b></span>)}</div>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:readonly (readonly [string,string])[]}){return <label><span>{label}</span><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>}
function NumberField({label,value,onChange,min,max,step=1}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number;step?:number}){return <label><span>{label}</span><input type="number" value={value} min={min} max={max} step={step} onChange={e=>Number.isFinite(e.target.valueAsNumber)&&onChange(e.target.valueAsNumber)}/></label>}
function Radar({values}:{values:number[]}){const points=values.map((v,i)=>{const angle=-Math.PI/2+i*Math.PI*2/values.length,r=66*v/100;return `${90+Math.cos(angle)*r},${90+Math.sin(angle)*r}`}).join(" ");return <svg className="radar" viewBox="0 0 180 180">{[22,44,66].map(r=><polygon key={r} points={values.map((_,i)=>{const a=-Math.PI/2+i*Math.PI*2/values.length;return `${90+Math.cos(a)*r},${90+Math.sin(a)*r}`}).join(" ")}/>) }<polygon className="radar-value" points={points}/></svg>}
function Timeline({values}:{values:number[]}){const safe=values.length?values:[0],max=Math.max(...safe,1),min=Math.min(...safe),points=safe.map((v,i)=>`${10+i*(280/Math.max(1,safe.length-1))},${100-(v-min)/Math.max(1,max-min)*80}`).join(" ");return <svg className="timeline" viewBox="0 0 300 115"><path d="M10 100H290"/><polyline points={points}/>{safe.map((v,i)=><circle key={i} cx={10+i*(280/Math.max(1,safe.length-1))} cy={100-(v-min)/Math.max(1,max-min)*80} r="3"/>)}</svg>}
